language: java

jdk:
    - oraclejdk8

notifications:
    email: true

install:
    - git clone https://github.com/mondo-project/mondo-hawk/
    - cd mondo-hawk && ./install-maven-deps.sh
    - mvn -f pom-plain.xml install -pl \!standalone/_hawk_runtime_example
    - cd $TRAVIS_BUILD_DIR/ && mvn clean
    - cd $TRAVIS_BUILD_DIR/ && mvn install -DskipTests
